import { pendingStory } from "./story.js";

export const stories = [
  pendingStory({
    id: "accordion",
    title: "Accordion",
    group: "Actions & disclosure",
    rustStory: "AccordionStory",
    description: "Expandable content sections.",
    states: ["collapsed", "expanded", "disabled"],
    availability: "pending",
    api: "Accordion",
  }),
  pendingStory({
    id: "alert",
    title: "Alert",
    group: "Actions & disclosure",
    rustStory: "AlertStory",
    description: "Inline status messages.",
    states: ["info", "success", "warning", "destructive"],
    availability: "pending",
    api: "Alert",
  }),
  pendingStory({
    id: "button",
    title: "Button",
    group: "Actions & disclosure",
    rustStory: "ButtonStory",
    description: "Primary action control.",
    states: ["normal", "focused", "disabled", "loading", "destructive"],
    availability: "pending",
    api: "Button",
  }),
  pendingStory({
    id: "checkbox",
    title: "Checkbox",
    group: "Actions & disclosure",
    rustStory: "CheckboxStory",
    description: "Controlled binary selection.",
    states: ["unchecked", "checked", "disabled"],
    availability: "pending",
    api: "Checkbox",
  }),
  pendingStory({
    id: "clipboard",
    title: "Clipboard",
    group: "Actions & disclosure",
    rustStory: "ClipboardStory",
    description: "Copy and paste actions.",
    states: ["copy", "copied", "permission denied"],
    availability: "pending",
    api: "Clipboard",
  }),
  pendingStory({
    id: "collapsible",
    title: "Collapsible",
    group: "Actions & disclosure",
    rustStory: "CollapsibleStory",
    description: "A single expandable region.",
    states: ["collapsed", "expanded", "disabled"],
    availability: "pending",
    api: "Collapsible",
  }),
  pendingStory({
    id: "dropdown-button",
    title: "DropdownButton",
    group: "Actions & disclosure",
    rustStory: "DropdownButtonStory",
    description: "Action button with a menu.",
    states: ["normal", "open", "disabled"],
    availability: "pending",
    api: "DropdownButton",
  }),
  pendingStory({
    id: "toggle",
    title: "Toggle",
    group: "Actions & disclosure",
    rustStory: "ToggleStory",
    description: "Pressed-state button.",
    states: ["off", "on", "disabled"],
    availability: "pending",
    api: "Toggle",
  }),
  pendingStory({
    id: "switch",
    title: "Switch",
    group: "Actions & disclosure",
    rustStory: "SwitchStory",
    description: "Binary setting control.",
    states: ["off", "on", "disabled"],
    availability: "pending",
    api: "Switch",
  }),
];
