import { pendingStory } from "./story.js";

export const stories = [
  pendingStory({
    id: "command",
    title: "Command",
    group: "Collections & data",
    rustStory: "CommandStory",
    description: "Command palette and command items.",
    states: ["empty", "filtered", "keyboard selection"],
    availability: "pending",
    api: "Command",
  }),
  pendingStory({
    id: "data-table",
    title: "DataTable",
    group: "Collections & data",
    rustStory: "DataTableStory",
    description: "Structured sortable data grid.",
    states: ["rows", "selected", "loading", "empty"],
    availability: "pending",
    api: "DataTable",
  }),
  pendingStory({
    id: "form",
    title: "Form",
    group: "Collections & data",
    rustStory: "FormStory",
    description: "Validated grouped controls.",
    states: ["normal", "validation", "disabled"],
    availability: "pending",
    api: "Form",
  }),
  pendingStory({
    id: "list",
    title: "List",
    group: "Collections & data",
    rustStory: "ListStory",
    description: "Selectable list of retained items.",
    states: ["normal", "selected", "loading", "empty"],
    availability: "pending",
    api: "List",
  }),
  pendingStory({
    id: "settings",
    title: "Settings",
    group: "Collections & data",
    rustStory: "SettingsStory",
    description: "Settings pages and field groups.",
    states: ["default page", "changed", "disabled"],
    availability: "pending",
    api: "Settings",
  }),
  pendingStory({
    id: "table",
    title: "Table",
    group: "Collections & data",
    rustStory: "TableStory",
    description: "Table layout primitives.",
    states: ["normal", "striped", "empty"],
    availability: "pending",
    api: "Table",
  }),
  pendingStory({
    id: "tree",
    title: "Tree",
    group: "Collections & data",
    rustStory: "TreeStory",
    description: "Nested selectable data.",
    states: ["collapsed", "expanded", "selected"],
    availability: "pending",
    api: "Tree",
  }),
  pendingStory({
    id: "virtual-list",
    title: "VirtualList",
    group: "Collections & data",
    rustStory: "VirtualListStory",
    description: "Large retained collection virtualization.",
    states: ["initial", "scrolled", "loading"],
    availability: "infrastructure",
    api: "VirtualList",
  }),
];
