import { pendingStory } from "./story.js";

export const stories = [
  pendingStory({
    id: "attachment",
    title: "Attachment",
    group: "Content",
    rustStory: "AttachmentStory",
    description: "File and image attachment metadata.",
    states: ["pending", "uploading", "failed", "complete"],
    availability: "pending",
    api: "Attachment",
  }),
  pendingStory({
    id: "avatar",
    title: "Avatar",
    group: "Content",
    rustStory: "AvatarStory",
    description: "Person and group identity.",
    states: ["image", "initials", "fallback"],
    availability: "pending",
    api: "Avatar",
  }),
  pendingStory({
    id: "badge",
    title: "Badge",
    group: "Content",
    rustStory: "BadgeStory",
    description: "Compact semantic label.",
    states: ["neutral", "success", "warning", "destructive"],
    availability: "pending",
    api: "Badge",
  }),
  pendingStory({
    id: "bubble",
    title: "Bubble",
    group: "Content",
    rustStory: "BubbleStory",
    description: "Aligned conversation content surface.",
    states: ["filled", "secondary", "outline", "destructive"],
    availability: "pending",
    api: "Bubble",
  }),
  pendingStory({
    id: "description-list",
    title: "DescriptionList",
    group: "Content",
    rustStory: "DescriptionListStory",
    description: "Key-value metadata display.",
    states: ["stacked", "inline"],
    availability: "pending",
    api: "DescriptionList",
  }),
  pendingStory({
    id: "group-box",
    title: "GroupBox",
    group: "Content",
    rustStory: "GroupBoxStory",
    description: "Labeled content container.",
    states: ["normal", "disabled"],
    availability: "pending",
    api: "GroupBox",
  }),
  pendingStory({
    id: "progress",
    title: "Progress",
    group: "Content",
    rustStory: "ProgressStory",
    description: "Determinate and indeterminate progress.",
    states: ["0%", "50%", "complete", "loading"],
    availability: "pending",
    api: "Progress",
  }),
  pendingStory({
    id: "marker",
    title: "Marker",
    group: "Content",
    rustStory: "MarkerStory",
    description: "Conversation status and loading marker.",
    states: ["plain", "separator", "loading"],
    availability: "pending",
    api: "Marker",
  }),
  pendingStory({
    id: "message",
    title: "Message",
    group: "Content",
    rustStory: "MessageStory",
    description: "Structured leading or trailing message row.",
    states: ["incoming", "outgoing"],
    availability: "pending",
    api: "Message",
  }),
  pendingStory({
    id: "message-scroller",
    title: "MessageScroller",
    group: "Content",
    rustStory: "MessageScrollerStory",
    description: "Virtualized transcript with tail following.",
    states: ["following", "scrolled-up"],
    availability: "pending",
    api: "MessageScroller",
  }),
  pendingStory({
    id: "skeleton",
    title: "Skeleton",
    group: "Content",
    rustStory: "SkeletonStory",
    description: "Loading placeholders.",
    states: ["text", "avatar", "card"],
    availability: "pending",
    api: "Skeleton",
  }),
  pendingStory({
    id: "spinner",
    title: "Spinner",
    group: "Content",
    rustStory: "SpinnerStory",
    description: "Indeterminate loading indicator.",
    states: ["normal", "muted", "large"],
    availability: "pending",
    api: "Spinner",
  }),
  pendingStory({
    id: "shimmer",
    title: "ShimmerText",
    group: "Content",
    rustStory: "ShimmerStory",
    description: "Theme-aware animated loading text.",
    states: ["looping", "reverse", "once"],
    availability: "pending",
    api: "ShimmerText",
  }),
  pendingStory({
    id: "tag",
    title: "Tag",
    group: "Content",
    rustStory: "TagStory",
    description: "Removable metadata token.",
    states: ["normal", "selected", "disabled"],
    availability: "pending",
    api: "Tag",
  }),
];
