import { pendingStory } from "./story.js";

export const stories = [
  pendingStory({
    id: "introduction",
    title: "Introduction",
    group: "Foundations",
    rustStory: "WelcomeStory",
    description: "Gallery overview and JavaScript API status.",
    states: ["catalog coverage", "public-module boundary"],
    api: "Welcome",
  }),
  pendingStory({
    id: "icon",
    title: "Icon",
    group: "Foundations",
    rustStory: "IconStory",
    description: "Named and custom icons.",
    states: ["normal", "muted", "destructive"],
    availability: "pending",
    api: "Icon",
  }),
  pendingStory({
    id: "image",
    title: "Image",
    group: "Foundations",
    rustStory: "ImageStory",
    description: "Image loading and sizing.",
    states: ["loaded", "loading", "error"],
    availability: "pending",
    api: "Image",
  }),
  pendingStory({
    id: "label",
    title: "Label",
    group: "Foundations",
    rustStory: "LabelStory",
    description: "Text labels and semantic emphasis.",
    states: ["normal", "disabled", "selected"],
    availability: "pending",
    api: "Label",
  }),
  pendingStory({
    id: "kbd",
    title: "Kbd",
    group: "Foundations",
    rustStory: "KbdStory",
    description: "Keyboard shortcut notation.",
    states: ["single key", "key chord"],
    availability: "pending",
    api: "Kbd",
  }),
  pendingStory({
    id: "separator",
    title: "Separator",
    group: "Foundations",
    rustStory: "SeparatorStory",
    description: "Horizontal and vertical dividers.",
    states: ["horizontal", "vertical"],
    availability: "pending",
    api: "Separator",
  }),
  pendingStory({
    id: "status-bar",
    title: "StatusBar",
    group: "Foundations",
    rustStory: "StatusBarStory",
    description: "Application status surfaces.",
    states: ["normal", "warning", "loading"],
    availability: "pending",
    api: "StatusBar",
  }),
];
