import { pendingStory } from "./story.js";

export const stories = [
  pendingStory({
    id: "input",
    title: "Input",
    group: "Inputs",
    rustStory: "InputStory",
    description: "Single-line retained text input.",
    states: ["normal", "focused", "disabled", "validation"],
    availability: "pending",
    api: "Input",
  }),
  pendingStory({
    id: "textarea",
    title: "Textarea",
    group: "Inputs",
    rustStory: "TextareaStory",
    description: "Multi-line retained text input.",
    states: ["normal", "focused", "validation"],
    availability: "pending",
    api: "Textarea",
  }),
  pendingStory({
    id: "number-input",
    title: "NumberInput",
    group: "Inputs",
    rustStory: "NumberInputStory",
    description: "Stepped numeric input.",
    states: ["normal", "min/max", "disabled"],
    availability: "pending",
    api: "NumberInput",
  }),
  pendingStory({
    id: "otp-input",
    title: "OtpInput",
    group: "Inputs",
    rustStory: "OtpInputStory",
    description: "One-time-code input.",
    states: ["empty", "filled", "validation"],
    availability: "pending",
    api: "OtpInput",
  }),
  pendingStory({
    id: "select",
    title: "Select",
    group: "Inputs",
    rustStory: "SelectStory",
    description: "Controlled picker.",
    states: ["closed", "open", "disabled", "validation"],
    availability: "pending",
    api: "Select",
  }),
  pendingStory({
    id: "combobox",
    title: "Combobox",
    group: "Inputs",
    rustStory: "ComboboxStory",
    description: "Searchable controlled picker.",
    states: ["empty", "filtered", "loading", "disabled"],
    availability: "pending",
    api: "Combobox",
  }),
  pendingStory({
    id: "radio",
    title: "Radio",
    group: "Inputs",
    rustStory: "RadioStory",
    description: "Exclusive choice group.",
    states: ["unselected", "selected", "disabled"],
    availability: "pending",
    api: "Radio",
  }),
  pendingStory({
    id: "slider",
    title: "Slider",
    group: "Inputs",
    rustStory: "SliderStory",
    description: "Continuous and range values.",
    states: ["single value", "range", "disabled"],
    availability: "pending",
    api: "Slider",
  }),
  pendingStory({
    id: "color-picker",
    title: "ColorPicker",
    group: "Inputs",
    rustStory: "ColorPickerStory",
    description: "Color selection.",
    states: ["closed", "open", "disabled"],
    availability: "pending",
    api: "ColorPicker",
  }),
  pendingStory({
    id: "rating",
    title: "Rating",
    group: "Inputs",
    rustStory: "RatingStory",
    description: "Star-style selection.",
    states: ["empty", "selected", "disabled"],
    availability: "pending",
    api: "Rating",
  }),
];
