import { pendingStory } from "./story.js";

export const stories = [
  pendingStory({
    id: "calendar",
    title: "Calendar",
    group: "Layout & advanced",
    rustStory: "CalendarStory",
    description: "Date grid and range selection.",
    states: ["month", "selected day", "range"],
    availability: "pending",
    api: "Calendar",
  }),
  pendingStory({
    id: "chart",
    title: "Chart",
    group: "Layout & advanced",
    rustStory: "ChartStory",
    description: "Data visualizations.",
    states: ["line", "bar", "area", "empty"],
    availability: "pending",
    api: "BarChart",
  }),
  pendingStory({
    id: "date-picker",
    title: "DatePicker",
    group: "Layout & advanced",
    rustStory: "DatePickerStory",
    description: "Date input with calendar overlay.",
    states: ["empty", "selected", "disabled"],
    availability: "pending",
    api: "DatePicker",
  }),
  pendingStory({
    id: "dock",
    title: "Dock",
    group: "Layout & advanced",
    rustStory: "DockStory",
    description: "Dockable panel layout.",
    states: ["split", "tab group", "side dock", "dragging"],
    availability: "infrastructure",
    api: "Dock",
  }),
  pendingStory({
    id: "editor",
    title: "Editor",
    group: "Layout & advanced",
    rustStory: "EditorStory",
    description: "Rich text editor state.",
    states: ["editing", "selection", "diagnostic"],
    availability: "pending",
    api: "Editor",
  }),
  pendingStory({
    id: "resizable",
    title: "Resizable",
    group: "Layout & advanced",
    rustStory: "ResizableStory",
    description: "Resizable panel groups.",
    states: ["horizontal", "vertical", "collapsed"],
    availability: "pending",
    api: "Resizable",
  }),
  pendingStory({
    id: "scrollbar",
    title: "Scrollbar",
    group: "Layout & advanced",
    rustStory: "ScrollbarStory",
    description: "Scrollable content and native scrollbars.",
    states: ["vertical", "horizontal", "masked"],
    availability: "pending",
    api: "Scrollbar",
  }),
];
