import { pendingStory } from "./story.js";

export const stories = [
  pendingStory({
    id: "breadcrumb",
    title: "Breadcrumb",
    group: "Navigation",
    rustStory: "BreadcrumbStory",
    description: "Hierarchical path navigation.",
    states: ["normal", "disabled item"],
    availability: "pending",
    api: "Breadcrumb",
  }),
  pendingStory({
    id: "pagination",
    title: "Pagination",
    group: "Navigation",
    rustStory: "PaginationStory",
    description: "Page selection controls.",
    states: ["first page", "middle page", "compact"],
    availability: "pending",
    api: "Pagination",
  }),
  pendingStory({
    id: "sidebar",
    title: "Sidebar",
    group: "Navigation",
    rustStory: "SidebarStory",
    description: "Collapsible application navigation.",
    states: ["expanded", "collapsed", "selected"],
    availability: "pending",
    api: "Sidebar",
  }),
  pendingStory({
    id: "tabs",
    title: "Tabs",
    group: "Navigation",
    rustStory: "TabsStory",
    description: "Controlled tab selection.",
    states: ["selected", "disabled", "overflow"],
    availability: "pending",
    api: "TabBar",
  }),
  pendingStory({
    id: "stepper",
    title: "Stepper",
    group: "Navigation",
    rustStory: "StepperStory",
    description: "Sequential progress navigation.",
    states: ["current", "complete", "disabled"],
    availability: "pending",
    api: "Stepper",
  }),
];
