import { pendingStory } from "./story.js";

export const stories = [
  pendingStory({
    id: "alert-dialog",
    title: "AlertDialog",
    group: "Overlays",
    rustStory: "AlertDialogStory",
    description: "Destructive confirmation dialog.",
    states: ["open", "cancel", "destructive action"],
    availability: "pending",
    api: "AlertDialog",
  }),
  pendingStory({
    id: "dialog",
    title: "Dialog",
    group: "Overlays",
    rustStory: "DialogStory",
    description: "Modal content and focus restoration.",
    states: ["closed", "open", "dismissed"],
    availability: "pending",
    api: "Dialog",
  }),
  pendingStory({
    id: "hover-card",
    title: "HoverCard",
    group: "Overlays",
    rustStory: "HoverCardStory",
    description: "Pointer-triggered contextual information.",
    states: ["closed", "open", "delayed"],
    availability: "pending",
    api: "HoverCard",
  }),
  pendingStory({
    id: "menu",
    title: "Menu",
    group: "Overlays",
    rustStory: "MenuStory",
    description: "Context and dropdown menus.",
    states: ["closed", "open", "disabled item"],
    availability: "pending",
    api: "MenuBar",
  }),
  pendingStory({
    id: "native-menu",
    title: "NativeMenu",
    group: "Overlays",
    rustStory: "NativeMenuStory",
    description: "Platform application menu.",
    states: ["macOS", "Windows", "fallback"],
    availability: "platform",
    api: "NativeMenuTrigger",
  }),
  pendingStory({
    id: "notification",
    title: "Notification",
    group: "Overlays",
    rustStory: "NotificationStory",
    description: "Transient application notifications.",
    states: ["info", "success", "warning", "destructive"],
    availability: "pending",
    api: "Notification",
  }),
  pendingStory({
    id: "popover",
    title: "Popover",
    group: "Overlays",
    rustStory: "PopoverStory",
    description: "Anchored interactive overlay.",
    states: ["closed", "open", "dismissed"],
    availability: "pending",
    api: "Popover",
  }),
  pendingStory({
    id: "sheet",
    title: "Sheet",
    group: "Overlays",
    rustStory: "SheetStory",
    description: "Window-attached overlay sheet.",
    states: ["closed", "open", "validation"],
    availability: "pending",
    api: "Sheet",
  }),
  pendingStory({
    id: "tooltip",
    title: "Tooltip",
    group: "Overlays",
    rustStory: "TooltipStory",
    description: "Accessible compact help overlay.",
    states: ["hidden", "visible", "keyboard focus"],
    availability: "pending",
    api: "Tooltip",
  }),
];
